type Quality='high'|'medium'|'low';
const canvas=document.querySelector<HTMLCanvasElement>('#hero-webgl');
const reduceMotion=matchMedia('(prefers-reduced-motion: reduce)').matches;

if(canvas){
  const gl=canvas.getContext('webgl2',{alpha:true,antialias:false,powerPreference:'high-performance',depth:false,stencil:false});
  if(!gl){document.documentElement.classList.add('no-webgl');canvas.hidden=true;}else{
    const compile=(type:number,source:string)=>{const shader=gl.createShader(type);if(!shader)throw new Error('shader allocation failed');gl.shaderSource(shader,source);gl.compileShader(shader);if(!gl.getShaderParameter(shader,gl.COMPILE_STATUS)){const msg=gl.getShaderInfoLog(shader)||'shader compile failed';gl.deleteShader(shader);throw new Error(msg);}return shader;};
    try{
      const vs=compile(gl.VERTEX_SHADER,`#version 300 es\nout vec2 vUv;void main(){vec2 p=vec2(float((gl_VertexID<<1)&2),float(gl_VertexID&2));vUv=p*.5;gl_Position=vec4(p-1.,0.,1.);}`);
      const fs=compile(gl.FRAGMENT_SHADER,`#version 300 es\nprecision highp float;in vec2 vUv;out vec4 outColor;uniform float uTime;uniform vec2 uResolution;uniform vec2 uPointer;uniform float uScroll;float hash21(vec2 p){p=fract(p*vec2(123.34,456.21));p+=dot(p,p+45.32);return fract(p.x*p.y);}float line(float d,float w){return 1.-smoothstep(w,w+.0025,abs(d));}mat2 rot(float a){float s=sin(a),c=cos(a);return mat2(c,-s,s,c);}void main(){vec2 uv=vUv,p=uv-.5;p.x*=uResolution.x/max(uResolution.y,1.);vec2 mp=uPointer-.5;mp.x*=uResolution.x/max(uResolution.y,1.);float t=uTime*.14;vec3 night=vec3(0.,.025,.13),blue=vec3(0.,.247,.56),electric=vec3(.055,.294,.631),cyan=vec3(.043,.706,.843),magenta=vec3(.776,.337,.667),coral=vec3(.882,.306,.22);vec3 color=mix(night,blue*.72,smoothstep(.95,-.2,length(p)));vec2 q=p;q+=.035*vec2(sin(q.y*8.+t*3.),cos(q.x*7.-t*2.));q+=(mp-p)*.032/(.25+dot(mp-p,mp-p));vec2 guv=q*7.;vec2 grid=abs(fract(guv-.5)-.5)/fwidth(guv);float gridLine=1.-min(min(grid.x,grid.y),1.);color+=electric*gridLine*.075;vec2 center=vec2(.28,.02);float r=length(q-center);float rings=line(fract(r*4.8-t*.45)-.5,.035)*smoothstep(1.,.05,r);color+=cyan*rings*.20;vec2 rp=(q-center)*rot(-.12-uScroll*.28);float beamA=line(rp.y-sin(rp.x*2.7+t)*.05,.008),beamB=line(rp.y+.25-cos(rp.x*3.1-t*.8)*.04,.004);color+=cyan*beamA*.33+magenta*beamB*.20;vec2 cells=floor((q+vec2(1.4,.95))*20.),local=fract((q+vec2(1.4,.95))*20.)-.5;float rnd=hash21(cells),dotShape=1.-smoothstep(.08,.15,length(local)),active=step(.82,rnd)*dotShape;color+=mix(cyan,magenta,step(.93,rnd))*active*.46*smoothstep(1.1,.15,length(q));vec2 anomaly=q-vec2(.56,-.22);float crossA=line(anomaly.x,.006)*smoothstep(.095,.07,abs(anomaly.y)),crossB=line(anomaly.y,.006)*smoothstep(.095,.07,abs(anomaly.x));color+=coral*(crossA+crossB)*(.72+.28*sin(uTime*1.4));float glow=exp(-5.5*length(q-center));color+=cyan*glow*.17;float scan=exp(-80.*abs(uv.y-fract(t*.07+uScroll*.28)));color+=vec3(.18,.48,.72)*scan*.065;float vignette=smoothstep(.95,.28,length(p*vec2(.78,1.)));color*=.72+vignette*.36;color+=(hash21(gl_FragCoord.xy+floor(uTime*24.))-.5)*.025;outColor=vec4(color,1.);}`);
      const program=gl.createProgram();if(!program)throw new Error('program allocation failed');gl.attachShader(program,vs);gl.attachShader(program,fs);gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(program)||'program link failed');gl.deleteShader(vs);gl.deleteShader(fs);gl.useProgram(program);
      const locTime=gl.getUniformLocation(program,'uTime'),locRes=gl.getUniformLocation(program,'uResolution'),locPointer=gl.getUniformLocation(program,'uPointer'),locScroll=gl.getUniformLocation(program,'uScroll');
      const mobile=matchMedia('(max-width:760px)').matches,cores=navigator.hardwareConcurrency||4,memory=(navigator as Navigator&{deviceMemory?:number}).deviceMemory||4;let quality:Quality=mobile||cores<=4||memory<=4?'low':cores<=8?'medium':'high';let time=0,scroll=0,px=.5,py=.5,tpx=.5,tpy=.5,running=false,raf=0,last=performance.now(),frames=0,sampleStart=last;
      const scale=()=>quality==='high'?1:quality==='medium'?.82:.62;
      const resize=()=>{const r=canvas.getBoundingClientRect(),maxPixels=mobile?900000:quality==='high'?2200000:1500000,native=Math.min(devicePixelRatio||1,quality==='high'?1.6:1.25),desired=r.width*r.height*native*native,dpr=Math.max(.65,native*(desired>maxPixels?Math.sqrt(maxPixels/desired):1)*scale());canvas.width=Math.max(1,Math.floor(r.width*dpr));canvas.height=Math.max(1,Math.floor(r.height*dpr));gl.viewport(0,0,canvas.width,canvas.height);};
      const draw=(now:number)=>{if(!running)return;const dt=Math.min(32,now-last);last=now;if(!reduceMotion)time+=dt*.001;px+=(tpx-px)*.055;py+=(tpy-py)*.055;gl.useProgram(program);gl.uniform1f(locTime,time);gl.uniform2f(locRes,canvas.width,canvas.height);gl.uniform2f(locPointer,px,py);gl.uniform1f(locScroll,scroll);gl.drawArrays(gl.TRIANGLES,0,3);frames++;if(!reduceMotion&&now-sampleStart>2600){const fps=frames*1000/(now-sampleStart);if(fps<43&&quality!=='low'){quality=quality==='high'?'medium':'low';resize();}frames=0;sampleStart=now;}if(!reduceMotion)raf=requestAnimationFrame(draw);};
      const start=()=>{if(running)return;running=true;last=performance.now();if(reduceMotion){draw(last);running=false;}else raf=requestAnimationFrame(draw);};const stop=()=>{running=false;cancelAnimationFrame(raf);};
      resize();start();document.documentElement.classList.add('has-webgl');
      canvas.addEventListener('pointermove',e=>{const r=canvas.getBoundingClientRect();tpx=Math.max(0,Math.min(1,(e.clientX-r.left)/r.width));tpy=Math.max(0,Math.min(1,1-(e.clientY-r.top)/r.height));},{passive:true});canvas.addEventListener('pointerleave',()=>{tpx=tpy=.5;},{passive:true});addEventListener('resize',resize,{passive:true});
      const io=new IntersectionObserver(([entry])=>entry.isIntersecting?start():stop(),{threshold:.01});io.observe(canvas);document.addEventListener('visibilitychange',()=>document.hidden?stop():start());window.addEventListener('dixios:hero-scroll',((e:CustomEvent<number>)=>{scroll=e.detail;}) as EventListener);window.addEventListener('pagehide',()=>{stop();io.disconnect();gl.deleteProgram(program);},{once:true});
    }catch(error){console.info('[Dixios] WebGL enhancement unavailable; using CSS/SVG fallback.',error);document.documentElement.classList.add('no-webgl');canvas.hidden=true;}
  }
}
